window.HF_SCENES = [
  {
    "id": "S01",
    "index": 1,
    "type": "hook",
    "title": "다섯 명이 들어갔다. 화면에는 여섯 명",
    "purpose": "다섯 명이 체크인했지만 CCTV에는 여섯 명",
    "start": 0.0,
    "end": 12.99,
    "duration": 12.99,
    "speechStart": 0.0,
    "speechEnd": 13.0,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "10% 42%",
    "metric": "5 → 6",
    "transition": "숫자 노이즈 컷"
  },
  {
    "id": "S02",
    "index": 2,
    "type": "setup",
    "title": "4년 만에 다시 모인 다섯 친구",
    "purpose": "4년 만에 모인 다섯 친구",
    "start": 12.99,
    "end": 37.29,
    "duration": 24.3,
    "speechStart": 13.34,
    "speechEnd": 37.06,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "42% 30%",
    "metric": "4년 만의 여행",
    "transition": "헤드라이트 매치컷"
  },
  {
    "id": "S03",
    "index": 3,
    "type": "isolation",
    "title": "7km 앞에서 길이 사라졌다",
    "purpose": "내비게이션 종료와 통신 두절",
    "start": 37.29,
    "end": 89.65,
    "duration": 52.36,
    "speechStart": 37.64,
    "speechEnd": 89.2,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "8% 45%",
    "metric": "신호 1칸",
    "transition": "노란 등불로 디졸브"
  },
  {
    "id": "S04",
    "index": 4,
    "type": "arrival",
    "title": "오후 6시 43분, 월영재",
    "purpose": "오후 6시 43분, 주인 없는 펜션",
    "start": 89.65,
    "end": 115.45,
    "duration": 25.8,
    "speechStart": 90.0,
    "speechEnd": 115.32,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "12% 40%",
    "metric": "18:43",
    "transition": "현관문 암전 컷"
  },
  {
    "id": "S05",
    "index": 5,
    "type": "evidence",
    "title": "컵도 여섯, 실내화도 여섯",
    "purpose": "컵과 실내화가 각각 여섯 개",
    "start": 115.45,
    "end": 136.61,
    "duration": 21.16,
    "speechStart": 115.8,
    "speechEnd": 136.14,
    "asset": "assets/visuals/dining-six-settings.png",
    "focus": "50% 55%",
    "metric": "컵 6개",
    "transition": "휴대전화 화면으로 푸시인"
  },
  {
    "id": "S06",
    "index": 6,
    "type": "evidence",
    "title": "예약 인원은 성인 여섯 명",
    "purpose": "예약 화면에 성인 여섯 명",
    "start": 136.61,
    "end": 155.09,
    "duration": 18.48,
    "speechStart": 136.96,
    "speechEnd": 154.52,
    "asset": "assets/visuals/dining-six-settings.png",
    "focus": "58% 52%",
    "metric": "성인 6명",
    "transition": "식탁 방향 휩팬"
  },
  {
    "id": "S07",
    "index": 7,
    "type": "uncanny",
    "title": "누가 여기 앉기로 했지?",
    "purpose": "혜진이 성호의 자리를 묻는다",
    "start": 155.09,
    "end": 189.87,
    "duration": 34.78,
    "speechStart": 155.44,
    "speechEnd": 189.9,
    "asset": "assets/visuals/dining-six-settings.png",
    "focus": "56% 45%",
    "metric": "빈 의자",
    "transition": "성호 이름에 맞춘 플래시"
  },
  {
    "id": "S08",
    "index": 8,
    "type": "memory",
    "title": "성호를 모두 기억했다",
    "purpose": "모두 성호를 알지만 관계가 다르다",
    "start": 189.87,
    "end": 236.29,
    "duration": 46.42,
    "speechStart": 190.22,
    "speechEnd": 235.88,
    "asset": "assets/visuals/stalled-car-photo-corruption.png",
    "focus": "55% 65%",
    "metric": "기억 불일치",
    "transition": "채팅창 글리치"
  },
  {
    "id": "S09",
    "index": 9,
    "type": "message",
    "title": "이번에는 꼭 여섯 명이 가야 해",
    "purpose": "여섯 번째 프로필과 하나뿐인 메시지",
    "start": 236.29,
    "end": 280.71,
    "duration": 44.42,
    "speechStart": 236.64,
    "speechEnd": 280.64,
    "asset": "assets/visuals/stalled-car-photo-corruption.png",
    "focus": "60% 72%",
    "metric": "참여자 6명",
    "transition": "진동 파형을 계단선으로 연결"
  },
  {
    "id": "S10",
    "index": 10,
    "type": "discovery",
    "title": "도면에 없는 네 번째 문",
    "purpose": "도면에 없는 문과 젖은 검은 코트",
    "start": 280.71,
    "end": 331.77,
    "duration": 51.06,
    "speechStart": 281.06,
    "speechEnd": 331.36,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "88% 28%",
    "metric": "도면 밖의 문",
    "transition": "전화 파형으로 하드컷"
  },
  {
    "id": "S11",
    "index": 11,
    "type": "warning",
    "title": "사람 수를 세지 마세요",
    "purpose": "현관 카메라를 확인하되 사람 수를 세지 말라",
    "start": 331.77,
    "end": 372.95,
    "duration": 41.18,
    "speechStart": 332.12,
    "speechEnd": 372.58,
    "asset": "assets/visuals/cctv-control-room.png",
    "focus": "52% 55%",
    "metric": "세지 마세요",
    "transition": "지하 모니터 점등"
  },
  {
    "id": "S12",
    "index": 12,
    "type": "cctv",
    "title": "차에서 여섯 번째가 내렸다",
    "purpose": "차에서 여섯 번째 사람이 내린다",
    "start": 372.95,
    "end": 432.13,
    "duration": 59.18,
    "speechStart": 373.3,
    "speechEnd": 432.16,
    "asset": "assets/visuals/cctv-control-room.png",
    "focus": "63% 42%",
    "metric": "입실 6명",
    "transition": "카운터 숫자 확대"
  },
  {
    "id": "S13",
    "index": 13,
    "type": "blackout",
    "title": "진짜 여섯 명이네",
    "purpose": "민석이 여섯 명이라고 말하는 순간 모니터가 꺼진다",
    "start": 432.13,
    "end": 458.35,
    "duration": 26.22,
    "speechStart": 432.48,
    "speechEnd": 458.0,
    "asset": "assets/visuals/cctv-control-room.png",
    "focus": "55% 55%",
    "metric": "한마디",
    "transition": "모니터 재점등"
  },
  {
    "id": "S14",
    "index": 14,
    "type": "double",
    "title": "한 명이 모자라",
    "purpose": "지하에 있는데 화면 속 식탁에는 여섯 명이 앉아 있다",
    "start": 458.35,
    "end": 508.23,
    "duration": 49.88,
    "speechStart": 458.7,
    "speechEnd": 508.26,
    "asset": "assets/visuals/cctv-control-room.png",
    "focus": "58% 45%",
    "metric": "한 명이 모자라",
    "transition": "한 명이 모자라 문구 글리치"
  },
  {
    "id": "S15",
    "index": 15,
    "type": "aftermath",
    "title": "거실은 여섯 명 몫이었다",
    "purpose": "거실이 여섯 사람 몫으로 복원된다",
    "start": 508.23,
    "end": 526.99,
    "duration": 18.76,
    "speechStart": 508.58,
    "speechEnd": 526.56,
    "asset": "assets/visuals/dining-six-settings.png",
    "focus": "50% 55%",
    "metric": "여섯 사람 몫",
    "transition": "차량 시동 컷"
  },
  {
    "id": "S16",
    "index": 16,
    "type": "escape",
    "title": "차는 움직이지 않았다",
    "purpose": "배터리 케이블이 빠지고 차가 멈춘다",
    "start": 526.99,
    "end": 542.33,
    "duration": 15.34,
    "speechStart": 527.34,
    "speechEnd": 542.0,
    "asset": "assets/visuals/stalled-car-photo-corruption.png",
    "focus": "30% 45%",
    "metric": "시동 실패",
    "transition": "조수석 거울 포커스"
  },
  {
    "id": "S17",
    "index": 17,
    "type": "corruption",
    "title": "모든 사진에 성호가 있었다",
    "purpose": "각자 휴대전화에 성호의 사진이 생긴다",
    "start": 542.33,
    "end": 594.33,
    "duration": 52.0,
    "speechStart": 542.68,
    "speechEnd": 593.94,
    "asset": "assets/visuals/stalled-car-photo-corruption.png",
    "focus": "62% 70%",
    "metric": "사진마다 6명",
    "transition": "차량 스피커 잡음"
  },
  {
    "id": "S18",
    "index": 18,
    "type": "trap",
    "title": "차 안은 다섯 자리야",
    "purpose": "라디오 음성과 스스로 잠기는 안전벨트",
    "start": 594.33,
    "end": 611.97,
    "duration": 17.64,
    "speechStart": 594.68,
    "speechEnd": 611.54,
    "asset": "assets/visuals/stalled-car-photo-corruption.png",
    "focus": "34% 55%",
    "metric": "다섯 자리",
    "transition": "벽시계 매치컷"
  },
  {
    "id": "S19",
    "index": 19,
    "type": "rules",
    "title": "빈자리에 이름이 생긴다",
    "purpose": "이름이 기억과 사진 속 빈자리를 차지한다",
    "start": 611.97,
    "end": 693.87,
    "duration": 81.9,
    "speechStart": 612.32,
    "speechEnd": 693.46,
    "asset": "assets/visuals/cctv-control-room.png",
    "focus": "55% 50%",
    "metric": "이름이 자리를 만든다",
    "transition": "붉은 노끈으로 색상 전환"
  },
  {
    "id": "S20",
    "index": 20,
    "type": "preparation",
    "title": "이름을 쓰고 노끈을 묶었다",
    "purpose": "손목에 이름을 쓰고 붉은 노끈으로 연결한다",
    "start": 693.87,
    "end": 728.81,
    "duration": 34.94,
    "speechStart": 694.22,
    "speechEnd": 728.42,
    "asset": "assets/visuals/red-rope-procession.png",
    "focus": "52% 58%",
    "metric": "이름 / 노끈",
    "transition": "손전등 빛으로 와이프"
  },
  {
    "id": "S21",
    "index": 21,
    "type": "procession",
    "title": "뒤돌지 마세요",
    "purpose": "뒤돌지 않고 현관으로 이동한다",
    "start": 728.81,
    "end": 778.57,
    "duration": 49.76,
    "speechStart": 729.16,
    "speechEnd": 778.44,
    "asset": "assets/visuals/red-rope-procession.png",
    "focus": "54% 52%",
    "metric": "뒤돌지 마세요",
    "transition": "번지는 손목 글자로 컷"
  },
  {
    "id": "S22",
    "index": 22,
    "type": "erosion",
    "title": "내 이름이 사라졌다",
    "purpose": "손목 이름이 사라지고 성호의 기억이 침투한다",
    "start": 778.57,
    "end": 826.93,
    "duration": 48.36,
    "speechStart": 778.92,
    "speechEnd": 826.88,
    "asset": "assets/visuals/red-rope-procession.png",
    "focus": "70% 48%",
    "metric": "성호",
    "transition": "캠코더 낙하 충격"
  },
  {
    "id": "S23",
    "index": 23,
    "type": "anchor",
    "title": "오늘은 우리 다섯 명",
    "purpose": "녹화된 화자의 목소리가 다섯 사람의 이름을 확인한다",
    "start": 826.93,
    "end": 858.06,
    "duration": 31.13,
    "speechStart": 827.28,
    "speechEnd": 857.6,
    "asset": "assets/visuals/red-rope-procession.png",
    "focus": "82% 72%",
    "metric": "우리 다섯 명",
    "transition": "현관 바깥 백색광"
  },
  {
    "id": "S24",
    "index": 24,
    "type": "exit",
    "title": "퇴실 인원, 다섯 명",
    "purpose": "눈밭으로 탈출하고 차가 출발한다",
    "start": 858.06,
    "end": 900.73,
    "duration": 42.67,
    "speechStart": 858.41,
    "speechEnd": 900.28,
    "asset": "assets/visuals/wolyeongjae-reference.png",
    "focus": "10% 44%",
    "metric": "퇴실 5명",
    "transition": "파출소 형광등 플리커"
  },
  {
    "id": "S25",
    "index": 25,
    "type": "identity",
    "title": "성함이 어떻게 되십니까?",
    "purpose": "네 친구가 화자를 기억하지 못한다",
    "start": 900.73,
    "end": 972.55,
    "duration": 71.82,
    "speechStart": 901.08,
    "speechEnd": 972.4,
    "asset": "assets/visuals/police-cctv-reversal.png",
    "focus": "45% 58%",
    "metric": "당신은 누구입니까",
    "transition": "메모리카드 삽입 컷"
  },
  {
    "id": "S26",
    "index": 26,
    "type": "reversal",
    "title": "나무 뒤에서 나온 사람",
    "purpose": "원래 다섯 명은 성호를 포함하고 화자는 밖에서 따라 들어온다",
    "start": 972.55,
    "end": 1088.47,
    "duration": 115.92,
    "speechStart": 972.9,
    "speechEnd": 1088.44,
    "asset": "assets/visuals/police-cctv-reversal.png",
    "focus": "67% 42%",
    "metric": "원래 다섯 명",
    "transition": "현재 방의 카메라 창으로 디졸브"
  },
  {
    "id": "S27",
    "index": 27,
    "type": "ending",
    "title": "이제 여섯 명이 됐네",
    "purpose": "방 안의 두 번째 컵과 화자 뒤의 젖은 검은 코트",
    "start": 1088.47,
    "end": 1153.031,
    "duration": 64.561,
    "speechStart": 1088.82,
    "speechEnd": 1152.9,
    "asset": "assets/visuals/final-two-glasses.png",
    "focus": "50% 55%",
    "metric": "이제 여섯 명",
    "transition": "완전 암전 후 1초 유지"
  }
];
