window.HF_SCENES = [
  {id:"S01",type:"hook",start:0,end:18.11,overlay:"warning",label:"존재하지 않는 층",visuals:["green-corridor","wallpad-dark","green-corridor"]},
  {id:"S02",type:"setup",start:18.11,end:43.35,overlay:"building",label:"세림아파트 104동",visuals:["apartment-exterior","separated-floor","apartment-exterior"]},
  {id:"S03",type:"hook",start:43.35,end:96.25,overlay:"phone",label:"마지막 통화",visuals:["wallpad-dark","elevator-panel","green-corridor","wallpad-dark"]},
  {id:"S04",type:"setup",start:96.25,end:114.77,overlay:"approach",label:"토요일 저녁",visuals:["apartment-exterior","green-corridor"]},
  {id:"S05",type:"evidence",start:114.77,end:173.83,overlay:"elevator",label:"정상적으로 존재했던 14층",visuals:["elevator-panel","green-corridor","elevator-panel","green-corridor"]},
  {id:"S06",type:"mystery",start:173.83,end:201.57,overlay:"absence",label:"사라진 어머니",visuals:["cold-dinner","wallpad-camera","cold-dinner"]},
  {id:"S07",type:"warning",start:201.57,end:222.41,overlay:"rules",label:"냉장고에 남은 규칙",visuals:["fridge-note","fire-door"]},
  {id:"S08",type:"evidence",start:222.41,end:264.81,overlay:"wallpad",label:"전원을 뽑아도 꺼지지 않았다",visuals:["wallpad-dark","wallpad-dark","green-corridor"]},
  {id:"S09",type:"anomaly",start:264.81,end:305.29,overlay:"skip",label:"14층을 건너뛰는 엘리베이터",visuals:["green-corridor","elevator-panel","green-corridor"]},
  {id:"S10",type:"threat",start:305.29,end:389.69,overlay:"voices",label:"문 밖의 목소리",visuals:["fire-door","corridor-two-lights","fire-door","green-corridor"]},
  {id:"S11",type:"countdown",start:389.69,end:413.59,overlay:"clocks",label:"03:17 직전",visuals:["stopped-clocks","wallpad-dark"]},
  {id:"S12",type:"evidence",start:413.59,end:447.61,overlay:"keynote",label:"벽장 안의 생존 규칙",visuals:["fridge-note","maintenance-records","fridge-note"]},
  {id:"S13",type:"reveal",start:447.61,end:484.43,overlay:"calls",label:"2006년의 부재중 전화",visuals:["wallpad-dark","faded-family-photo","fire-door"]},
  {id:"S14",type:"event",start:484.43,end:502.13,overlay:"separation",label:"건물에서 분리되는 14층",visuals:["separated-floor","apartment-exterior"]},
  {id:"S15",type:"threat",start:502.13,end:557.85,overlay:"camera",label:"집 안으로 들어온 카메라",visuals:["wallpad-camera","cold-dinner","wallpad-camera","green-corridor"]},
  {id:"S16",type:"rule",start:557.85,end:628.61,overlay:"doors",label:"호수를 말한 세대부터 삭제",visuals:["green-corridor","endless-corridor","green-corridor","fire-door"]},
  {id:"S17",type:"doubt",start:628.61,end:657.59,overlay:"double",label:"집 안과 문 밖의 두 어머니",visuals:["wallpad-camera","fire-door","corridor-two-lights"]},
  {id:"S18",type:"anomaly",start:657.59,end:685.93,overlay:"corridor",label:"물리적으로 늘어난 복도",visuals:["endless-corridor","green-corridor","endless-corridor"]},
  {id:"S19",type:"evidence",start:685.93,end:716.69,overlay:"eras",label:"문마다 다른 시대",visuals:["green-corridor","cold-dinner","faded-family-photo"]},
  {id:"S20",type:"evidence",start:716.69,end:770.95,overlay:"records",label:"10년마다 반복된 층 분리",visuals:["maintenance-records","separated-floor","maintenance-records"]},
  {id:"S21",type:"reveal",start:770.95,end:779.75,overlay:"missing",label:"2006년 미복귀",visuals:["maintenance-records"]},
  {id:"S22",type:"reveal",start:779.75,end:824.35,overlay:"memory",label:"20년 동안 이어진 흉내",visuals:["faded-family-photo","wallpad-camera","faded-family-photo"]},
  {id:"S23",type:"threat",start:824.35,end:844.53,overlay:"stereo",label:"양쪽에서 부르는 목소리",visuals:["corridor-two-lights","endless-corridor"]},
  {id:"S24",type:"countdown",start:844.53,end:871.71,overlay:"reassign",label:"미등록 거주자 재배정",visuals:["wallpad-dark","green-corridor","wallpad-dark"]},
  {id:"S25",type:"chase",start:871.71,end:893.93,overlay:"chase",label:"뒤에서 꺼지는 형광등",visuals:["stairwell-escape","endless-corridor"]},
  {id:"S26",type:"escape",start:893.93,end:940.21,overlay:"escape",label:"3시 31분, 13층",visuals:["stairwell-escape","fire-door","stairwell-escape"]},
  {id:"S27",type:"aftermath",start:940.21,end:971.31,overlay:"reality",label:"현실에서 사라진 한 층",visuals:["apartment-exterior","elevator-panel","apartment-exterior"]},
  {id:"S28",type:"reveal",start:971.31,end:1023.63,overlay:"documents",label:"주소와 사진까지 바뀌었다",visuals:["maintenance-records","faded-family-photo","cold-dinner"]},
  {id:"S29",type:"threat",start:1023.63,end:1047.51,overlay:"voicemail",label:"발신 번호 1402",visuals:["wallpad-dark","corridor-two-lights"]},
  {id:"S30",type:"calm",start:1047.51,end:1066.53,overlay:"newhome",label:"엘리베이터 없는 새집",visuals:["new-villa-wallpad","new-villa-wallpad"]},
  {id:"S31",type:"ending",start:1066.53,end:1073.99,overlay:"time",label:"다시, 03:17",visuals:["new-villa-wallpad","wallpad-dark"]},
  {id:"S32",type:"sting",start:1073.99,end:1101.42,overlay:"final",label:"1402호 재배정 완료",visuals:["wallpad-dark","new-villa-wallpad","fire-door"]},
  {id:"OUTRO",type:"outro",start:1101.42,end:1105.606,overlay:"outro",label:"",visuals:["new-villa-wallpad"]}
].map((scene,index)=>({...scene,index:index+1,duration:scene.end-scene.start}));
