import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
const P=path.dirname(new URL(import.meta.url).pathname),id=path.basename(P);
const read=n=>JSON.parse(fs.readFileSync(path.join(P,n),'utf8'));
const write=(n,v)=>fs.writeFileSync(path.join(P,n),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const plan=read('01_script/scene-plan.json');
const stamp=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
const mainTitle='장례식장 야간 청소 첫날, 영정사진 속 여자가 나왔다 | 공포괴담';
const chapters=[[0,'야간 청소 첫날'],[2,'젖은 맨발 자국'],[5,'사진에 찍힌 내 물건'],[8,'계단에 서 있는 사람'],[10,'문 아래의 움직임'],[12,'사진 속 빈자리'],[14,'흰 식탁보'],[17,'관리실 밖의 소리'],[20,'그날 이후'],[22,'돌려받은 작업복']].map(([i,t])=>`${stamp(plan.scenes[i].start_seconds)} ${t}`).join('\n');
const description=`장례식장 야간 청소 첫날, 빈소 바닥에 젖은 맨발 자국이 남아 있었습니다.\n유족이라고 생각했던 여자는 왜 자기 영정사진을 보고 있었을까요?\n사진 속 배경에 제 청소 카트가 보이기 시작했습니다.\n\n이어폰으로 들으면 발소리와 문밖의 기척을 더 가깝게 느낄 수 있습니다. 과도하게 큰 음량은 피해주세요.\n\n타임스탬프\n${chapters}\n\n이 영상은 어둠 속 이야기의 창작 공포입니다. 실제 인물·사건·장례식장과 관련이 없습니다. 이미지와 내레이션에 AI 생성 도구를 활용했습니다.\n\n다음 이야기: 「로봇청소기가 발견한 안쪽 방」\n채널의 공포괴담 본편 재생목록에서 이어서 감상해 주세요.\n\n#공포괴담 #무서운이야기 #장례식장괴담 #귀신이야기 #어둠속이야기`;
const common=[['메인 제목',mainTitle],['추천 제목 5가지','1. 빈소를 청소하는데 영정사진 속 여자가 복도에 서 있었다\n2. 사진을 엎어 놓자, 문밖의 발소리가 멈췄다 | 장례식장 괴담\n3. 아무도 없는 빈소의 영정사진에 내 청소 카트가 찍혔다\n4. 장례식장 야간 청소 첫날, 그 사진은 건드리면 안 됐다\n5. 돌아가신 분이 물었다. 왜 사진을 엎어 놨냐고'],['설명란',description],['태그','무서운이야기,공포괴담,장례식장괴담,영정사진,귀신이야기,야간청소,직업괴담,창작괴담,공포라디오,한국괴담,오디오드라마,어둠속이야기'],['고정 댓글','사진 속에 내 물건이 찍혀 있다면, 액자를 뒤집을 수 있을까요? 가장 소름 돋았던 장면을 남겨주세요.\n※ 이 이야기는 창작 공포입니다.'],['X 홍보문','아무도 없는 빈소를 청소하다 영정사진을 봤습니다.\n사진 속 배경에… 제 청소 카트가 찍혀 있었어요.\n\n장례식장 야간 청소 첫날 벌어진 이야기.\n[공개된 본편 URL 입력]\n#공포괴담 #무서운이야기'],['Threads 홍보문','사진 속 배경에 지금 내 옆에 있는 물건이 찍혀 있다면 어떨 것 같아요?\n이번 이야기는 장례식장 야간 청소 첫날에서 시작합니다. 사진을 뒤집은 다음부터는 발소리가 더 가까워집니다.\n창작 공포 「영정사진 속 여자」\n[공개된 본편 URL 입력]'],['Instagram 홍보문','사진 속 여자가 문밖에 서 있었습니다.\n장례식장 야간 청소 첫날, 영정사진에서 시작된 창작 공포.\n전체 이야기는 프로필의 유튜브 링크에서 확인해 주세요.\n#무서운이야기 #공포괴담 #장례식장괴담 #귀신이야기'],['업로드 체크','카테고리: 엔터테인먼트\n본편: 클린 MP4 / 외부 SRT 또는 VTT 업로드\n작품 성격: 창작 공포\n실제 같은 합성 장면이 포함되므로 YouTube의 변경·합성 콘텐츠 항목을 검토하고 해당하면 표시\n최종 18초: 관련 본편 또는 공포괴담 재생목록 엔드스크린 설정\n위 문구의 URL 입력 표시를 실제 공개 URL로 교체\n공개 전 미리보기와 음량 확인'],['추천 게시 시간','기본 실험 시간: 일요일 또는 수요일 오후 10시 (한국 시간)\n본편 공개 다음 날 오후 8시 30분에 쇼츠 공개를 권장합니다.\n이 시간은 채널 실측 최적값이 아닙니다. YouTube Studio 시청자 활동 데이터가 충분하면 활발한 시간 30~60분 전으로 조정하세요.\n실제 업로드나 예약은 실행하지 않았습니다.']];
const short=[['쇼츠 제목','영정사진에 내 물건이 찍혔다 #공포괴담'],['설명란','아무도 없는 빈소에서 사진을 뒤집었습니다.\n그러자 복도에서 젖은 발소리가 멈췄어요.\n문밖에 있던 사람의 이야기는 아래 관련 동영상에서 이어집니다.\n\n본편을 재구성한 독립 티저이며, 창작 공포입니다. AI 생성 이미지·음성이 사용됐습니다.\n#쇼츠 #무서운이야기 #장례식장괴담 #공포괴담'],['태그','공포쇼츠,무서운이야기,장례식장괴담,영정사진,귀신이야기,어둠속이야기'],['고정 댓글','사진을 엎었을 뿐인데 문밖에서 대답이 돌아왔습니다. 전체 이야기는 쇼츠의 관련 동영상에서 이어집니다.'],['본편 연결',`YouTube Studio → 이 쇼츠 → 관련 동영상\n선택할 본편: ${mainTitle}\n프로젝트: ${id}\n설명란 URL만으로 연결하지 마세요. 본편 게시 이후 정확한 영상을 지정하세요.`],['추천 게시 시간','본편 공개 다음 날 오후 8시 30분 (한국 시간). 본편이 먼저 공개되었는지 확인하고 관련 동영상을 연결하세요. 채널 분석 데이터에 따라 조정하는 초기 실험 시간입니다.']];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function make(fmt,blocks){const all=blocks.map(([h,t])=>h+'\n'+t).join('\n\n');const short=fmt==='shorts';const title=short?'쇼츠 게시 도우미':'유튜브 게시 도우미';
const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · 영정사진 속 여자</title><style>*{box-sizing:border-box}body{margin:0;background:#101218;color:#e9edf1;font-family:-apple-system,BlinkMacSystemFont,'Apple SD Gothic Neo',sans-serif;line-height:1.7}main{max-width:1000px;margin:auto;padding:40px 22px 80px}header{padding:30px;background:linear-gradient(130deg,#301c34,#17212c);border-radius:22px;margin-bottom:26px}h1{font-size:30px;line-height:1.3}h2{font-size:20px;margin:0}p{color:#b8bdc9}button,a.link{display:inline-block;border:1px solid #665177;background:#342741;color:white;padding:11px 18px;border-radius:10px;cursor:pointer;font-size:15px;text-decoration:none;margin:5px 6px 5px 0}button:hover{background:#54405f}section{padding:24px;margin:20px 0;background:#1a1e27;border:1px solid #333a46;border-radius:16px}.row{display:flex;justify-content:space-between;align-items:center;gap:15px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;margin:18px 0 0;color:#e2e5eb}video{width:100%;max-height:580px;background:#05070c;border-radius:12px}.thumbs{display:grid;grid-template-columns:1fr 1fr;gap:15px}.thumbs img{width:100%;border-radius:10px}#status{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);padding:10px 20px;border-radius:10px;background:#eff6ec;color:#172015;display:none}small{color:#b8bdc9}@media(max-width:600px){main{padding:20px 12px}header,section{padding:18px}.thumbs{grid-template-columns:1fr}.row{align-items:flex-start}h1{font-size:25px}}</style></head><body><main><header><small>어둠 속 이야기 · 창작 공포</small><h1>${title}</h1><p>영정사진 속 여자 · ${short?'독립 티저':'10분 52초 본편'} · 60fps</p><button id="copy-all">게시 내용 전체 복사</button><a class="link" href="../${short?'youtube/youtube':'shorts/shorts'}-publish.html">${short?'본편':'쇼츠'} 게시 도우미</a></header><section><h2>완성 영상</h2><video controls preload="metadata" src="../../06_delivery/${fmt}/${id}-${fmt}.mp4"></video><a class="link" href="../../06_delivery/${fmt}/${id}-${fmt}.mp4">영상 파일 열기</a><a class="link" href="../../03_sync/${short?'shorts-':''}captions.srt">SRT 자막</a><a class="link" href="../../03_sync/${short?'shorts-':''}captions.vtt">VTT 자막</a></section>${short?'':`<section id="thumbnails"><h2>썸네일 두 가지</h2><p>이미지를 눌러 원본 파일을 여세요.</p><div class="thumbs"><a href="thumbnail-a.jpg"><img src="thumbnail-a.jpg" alt="사진을 덮어 썸네일"></a><a href="thumbnail-b.jpg"><img src="thumbnail-b.jpg" alt="문밖은 누구 썸네일"></a></div></section>`}${blocks.map(([h,t],i)=>`<section><div class="row"><h2>${esc(h)}</h2><button data-copy="block-${i}">복사</button></div><pre id="block-${i}">${esc(t)}</pre></section>`).join('')}<p>파일 안의 내용은 게시 준비 자료입니다. 자동 게시·예약은 실행되지 않았습니다.</p></main><div id="status" role="status"></div><script>
const ALL=${JSON.stringify(all).replaceAll('<','\\u003c')};async function copyText(t){let ok=false;try{await navigator.clipboard.writeText(t);ok=true}catch{}if(!ok){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.top='0';a.style.left='-9999px';document.body.append(a);a.select();ok=document.execCommand('copy');a.remove()}const s=document.getElementById('status');s.textContent=ok?'복사했습니다':'복사하지 못했습니다. 내용을 선택해 복사해 주세요.';s.style.display='block';setTimeout(()=>s.style.display='none',2600);return ok}document.getElementById('copy-all').onclick=()=>copyText(ALL);document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyText(document.getElementById(b.dataset.copy).textContent));</script></body></html>`;
write(`07_publish/${fmt}/${short?'shorts':'youtube'}-publish.html`,html);
write(`07_publish/${fmt}/${short?'shorts':'youtube'}-publish.md`,'# '+title+'\n\n'+blocks.map(([h,t])=>'## '+h+'\n\n'+t).join('\n\n')+'\n');}
// From 07_publish/youtube, ../../ correctly resolves the project root.
make('youtube',common);make('shorts',short);
for(const key of ['a','b'])await sharp(path.join(P,`04_composition/assets/visuals/thumbnail-${key}.png`)).resize(1280,720,{fit:'cover'}).jpeg({quality:94}).toFile(path.join(P,`07_publish/youtube/thumbnail-${key}.jpg`));
write('07_publish/publish-data.json',{main_title:mainTitle,chapters,content_nature:'fiction',upload_executed:false});
