import fs from 'node:fs';
import path from 'node:path';
const p=path.dirname(new URL(import.meta.url).pathname);
const source=path.resolve(p,'../../planning',path.basename(p),'01_script');
const put=(n,v)=>fs.writeFileSync(path.join(p,n),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
let text=fs.readFileSync(path.join(source,'narration.txt'),'utf8');
text=text.replace('사진 속 여자는 제 어머니보다 조금 젊어 보였습니다.','사진 속 여자는 천을 씌운 의자에 앉아 있었어요. 제 어머니보다 조금 젊어 보였습니다.').replace('제가 걸어 둔 카트 잠금장치가 풀린 모양이었습니다.','잠겨 있던 카트 바퀴가 풀린 모양이었습니다.');
put('01_script/narration.txt',text);put('01_script/tts-narration.txt',text);
fs.copyFileSync(path.join(source,'scene-plan.md'),path.join(p,'01_script/scene-plan.md'));
const paras=text.trim().split(/\n\s*\n/);
const cfg=JSON.parse(fs.readFileSync(path.join(p,'02_audio/elevenlabs-request.json')));
cfg.request.voice_id='jB1Cifc2UQbq1gR3wnb0';delete cfg.bgm;put('02_audio/elevenlabs-request.json',cfg);
let t=0;const plan=JSON.parse(fs.readFileSync(path.join(p,'01_script/scene-plan.json')));
plan.scenes=paras.map((s,i)=>{const duration=s.split(/\s+/).length/127*60;const scene={id:'S'+String(i+1).padStart(2,'0'),type:'horror',start_seconds:t,end_seconds:t+duration,duration_seconds:duration,purpose:s.slice(0,45),narration_text:s,caption_text:s,visual:'planned cinematic image sequence',motion:'Story-specific light, focus and viewpoint changes every 1-3 seconds',motion_beats:[],audio:{intentional_silences:[]},transition_out:'cut',shorts_adaptation:'independent teaser'};t+=duration;return scene;});
plan.duration_seconds=t+4;plan.target_duration_seconds_range=[630,660];plan.timing_source='estimated';put('01_script/scene-plan.json',plan);
const shorts='영정사진 속에 제 청소 카트가 찍혀 있었어요.\n\n유리 반사가 아니었습니다. 액자를 기울여도 그대로였거든요.\n\n반장님은 사진을 당장 엎어 놓으라고 했죠.\n\n사진을 뒤집는 순간, 복도에서 젖은 발소리가 멈췄습니다.\n\n그리고 문 바로 밖에서 여자가 물었어요.\n\n왜 엎어 놨어요.\n';
put('01_script/shorts-narration.txt',shorts);put('01_script/shorts-tts-narration.txt',shorts);
put('02_audio/shorts-elevenlabs-request.json',{...cfg,script_source:'../01_script/shorts-narration.txt',tts_script_source:'../01_script/shorts-tts-narration.txt',target_audio:'inbox/'+path.basename(p)+'-shorts.mp3'});
for(const d of ['04_composition/assets/visuals','04_composition/assets/audio','05_review/logs','05_review/frames'])fs.mkdirSync(path.join(p,d),{recursive:true});
put('00_brief/brief.md','# 영정사진 속 여자\n\n창작 공포. 실제 인물이나 시설과 무관.\n\n사용자는 대본 검수를 맡기고 질문 없이 완성까지 진행하도록 명시적으로 승인했다. 이에 따라 본편 및 독립 쇼츠 대본의 경미한 개연성 보정, 추천 Bin 보이스, horror_cinematic_story_v1 / horror_cinematic, BGM 자율 선정과 검수 후 제작을 위임 승인으로 기록한다.\n\n최종 목표 630~660초, 이미지 48장. 1920x1080 60fps. 본편은 클린+외부 SRT/VTT, 쇼츠는 별도 1080x1920 60fps와 번인 자막. 기존 프로젝트와 전역 설정은 변경하지 않는다.\n');
