window.HF_SCENES = [
  {
    "id": "S01",
    "index": 1,
    "type": "hook",
    "purpose": "철거된 종탑에서 종이 울렸다는 사실로 시작한다",
    "start": 0.0,
    "end": 10.14,
    "duration": 10.14,
    "speechEnd": 9.3,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S02",
    "index": 2,
    "type": "context",
    "purpose": "저수율 9.4%라는 수치로 상황을 고정한다",
    "start": 10.14,
    "end": 27.5,
    "duration": 17.36,
    "speechEnd": 26.9,
    "overlay": "chart",
    "transition": "디졸브"
  },
  {
    "id": "S03",
    "index": 3,
    "type": "context",
    "purpose": "어머니의 고향이 물 아래라는 사실을 제시한다",
    "start": 27.5,
    "end": 47.1,
    "duration": 19.6,
    "speechEnd": 46.32,
    "overlay": "mapflood",
    "transition": "크로스 디졸브"
  },
  {
    "id": "S04",
    "index": 4,
    "type": "context",
    "purpose": "어머니가 고향을 말하지 않았다는 공백을 만든다",
    "start": 47.1,
    "end": 64.58,
    "duration": 17.48,
    "speechEnd": 63.9,
    "overlay": "photo",
    "transition": "페이드"
  },
  {
    "id": "S05",
    "index": 5,
    "type": "evidence",
    "purpose": "물 공포와 8월 불면이라는 복선을 심는다",
    "start": 64.58,
    "end": 91.58,
    "duration": 27.0,
    "speechEnd": 90.92,
    "overlay": "photo",
    "transition": "슬로 디졸브"
  },
  {
    "id": "S06",
    "index": 6,
    "type": "evidence",
    "purpose": "장례식에 아무도 오지 않았다는 사실을 남긴다",
    "start": 91.58,
    "end": 104.04,
    "duration": 12.46,
    "speechEnd": 103.16,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S07",
    "index": 7,
    "type": "evidence",
    "purpose": "마흔두 개의 이름이 적힌 수첩을 제시한다",
    "start": 104.04,
    "end": 131.34,
    "duration": 27.3,
    "speechEnd": 130.58,
    "overlay": "names",
    "transition": "디졸브"
  },
  {
    "id": "S08",
    "index": 8,
    "type": "turn",
    "purpose": "유골함을 싣고 저수지로 향한다",
    "start": 131.34,
    "end": 145.78,
    "duration": 14.44,
    "speechEnd": 144.94,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S09",
    "index": 9,
    "type": "context",
    "purpose": "폐허가 아니라 형태가 남은 마을을 보여준다",
    "start": 145.78,
    "end": 172.98,
    "duration": 27.2,
    "speechEnd": 172.54,
    "overlay": "photo",
    "transition": "슬로 팬"
  },
  {
    "id": "S10",
    "index": 10,
    "type": "evidence",
    "purpose": "직원이 어머니 이름을 듣고 말을 멈춘다",
    "start": 172.98,
    "end": 203.1,
    "duration": 30.12,
    "speechEnd": 202.84,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S11",
    "index": 11,
    "type": "turn",
    "purpose": "소리는 신경 쓰지 말라는 경고가 남는다",
    "start": 203.1,
    "end": 216.3,
    "duration": 13.2,
    "speechEnd": 215.6,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S12",
    "index": 12,
    "type": "context",
    "purpose": "마을 안으로 내려간다",
    "start": 216.3,
    "end": 233.34,
    "duration": 17.04,
    "speechEnd": 232.74,
    "overlay": "photo",
    "transition": "연속 컷"
  },
  {
    "id": "S13",
    "index": 13,
    "type": "evidence",
    "purpose": "첫 번째 집의 세간이 그대로 남아 있다",
    "start": 233.34,
    "end": 265.88,
    "duration": 32.54,
    "speechEnd": 265.02,
    "overlay": "photo",
    "transition": "디졸브"
  },
  {
    "id": "S14",
    "index": 14,
    "type": "evidence",
    "purpose": "두 번째와 세 번째 집도 같다",
    "start": 265.88,
    "end": 290.04,
    "duration": 24.16,
    "speechEnd": 289.2,
    "overlay": "cards",
    "transition": "크로스 페이드"
  },
  {
    "id": "S15",
    "index": 15,
    "type": "evidence",
    "purpose": "정미소 기계와 출석부가 남아 있다",
    "start": 290.04,
    "end": 332.14,
    "duration": 42.1,
    "speechEnd": 331.54,
    "overlay": "attendance",
    "transition": "하드컷"
  },
  {
    "id": "S16",
    "index": 16,
    "type": "evidence",
    "purpose": "시간표만 새것처럼 깨끗하다",
    "start": 332.14,
    "end": 348.22,
    "duration": 16.08,
    "speechEnd": 347.72,
    "overlay": "timetable",
    "transition": "디졸브"
  },
  {
    "id": "S17",
    "index": 17,
    "type": "turn",
    "purpose": "우물 걸쇠가 안쪽에 잠겨 있다",
    "start": 348.22,
    "end": 377.8,
    "duration": 29.58,
    "speechEnd": 377.04,
    "overlay": "latch",
    "transition": "하드컷"
  },
  {
    "id": "S18",
    "index": 18,
    "type": "evidence",
    "purpose": "세 집의 달력이 같은 날에 멈춰 있다",
    "start": 377.8,
    "end": 420.42,
    "duration": 42.62,
    "speechEnd": 420.34,
    "overlay": "calendars",
    "transition": "슬로 줌"
  },
  {
    "id": "S19",
    "index": 19,
    "type": "climax",
    "purpose": "없어야 할 종이 여섯 번 울린다",
    "start": 420.42,
    "end": 453.8,
    "duration": 33.38,
    "speechEnd": 453.0,
    "overlay": "certificate",
    "transition": "하드컷"
  },
  {
    "id": "S20",
    "index": 20,
    "type": "evidence",
    "purpose": "물리적 설명이 성립하지 않는다",
    "start": 453.8,
    "end": 482.94,
    "duration": 29.14,
    "speechEnd": 482.24,
    "overlay": "waves",
    "transition": "디졸브"
  },
  {
    "id": "S21",
    "index": 21,
    "type": "turn",
    "purpose": "사람들이 전부 올라가고 화자만 남는다",
    "start": 482.94,
    "end": 517.18,
    "duration": 34.24,
    "speechEnd": 516.52,
    "overlay": "photo",
    "transition": "슬로 페이드"
  },
  {
    "id": "S22",
    "index": 22,
    "type": "evidence",
    "purpose": "이주 처리 대장을 발견하고 읽는다",
    "start": 517.18,
    "end": 576.34,
    "duration": 59.16,
    "speechEnd": 575.64,
    "overlay": "ledger",
    "transition": "하드컷"
  },
  {
    "id": "S23",
    "index": 23,
    "type": "turn",
    "purpose": "수첩과 대장의 마흔두 개가 일치한다",
    "start": 576.34,
    "end": 597.82,
    "duration": 21.48,
    "speechEnd": 597.02,
    "overlay": "compare",
    "transition": "크로스 디졸브"
  },
  {
    "id": "S24",
    "index": 24,
    "type": "climax",
    "purpose": "도장 날짜가 전부 담수 당일이다",
    "start": 597.82,
    "end": 636.5,
    "duration": 38.68,
    "speechEnd": 635.98,
    "overlay": "stamps",
    "transition": "하드컷"
  },
  {
    "id": "S25",
    "index": 25,
    "type": "evidence",
    "purpose": "이장이 자기 이름 옆에도 도장을 찍었다",
    "start": 636.5,
    "end": 666.24,
    "duration": 29.74,
    "speechEnd": 665.5,
    "overlay": "hub",
    "transition": "디졸브"
  },
  {
    "id": "S26",
    "index": 26,
    "type": "turn",
    "purpose": "대피 방송과 함께 수위가 오르기 시작한다",
    "start": 666.24,
    "end": 699.36,
    "duration": 33.12,
    "speechEnd": 698.68,
    "overlay": "gauge",
    "transition": "하드컷"
  },
  {
    "id": "S27",
    "index": 27,
    "type": "climax",
    "purpose": "이주 예정지가 화자가 자란 집이다",
    "start": 699.36,
    "end": 729.74,
    "duration": 30.38,
    "speechEnd": 729.22,
    "overlay": "address",
    "transition": "슬로 줌"
  },
  {
    "id": "S28",
    "index": 28,
    "type": "turn",
    "purpose": "물 위의 발자국을 따라간다",
    "start": 729.74,
    "end": 775.08,
    "duration": 45.34,
    "speechEnd": 774.28,
    "overlay": "photo",
    "transition": "연속 컷"
  },
  {
    "id": "S29",
    "index": 29,
    "type": "climax",
    "purpose": "작은 부엌에 밥그릇이 마흔두 개 있다",
    "start": 775.08,
    "end": 813.8,
    "duration": 38.72,
    "speechEnd": 813.8,
    "overlay": "bowls",
    "transition": "하드컷"
  },
  {
    "id": "S30",
    "index": 30,
    "type": "reveal",
    "purpose": "수첩 마지막 장이 진실을 적어둔다",
    "start": 813.8,
    "end": 847.38,
    "duration": 33.58,
    "speechEnd": 846.66,
    "overlay": "letter",
    "transition": "슬로 디졸브"
  },
  {
    "id": "S31",
    "index": 31,
    "type": "reveal",
    "purpose": "이주한 것은 사람이 아니라 서류였다",
    "start": 847.38,
    "end": 900.08,
    "duration": 52.7,
    "speechEnd": 899.24,
    "overlay": "exodus",
    "transition": "크로스 디졸브"
  },
  {
    "id": "S32",
    "index": 32,
    "type": "climax",
    "purpose": "유골을 뿌리자 종이 사방에서 울린다",
    "start": 900.08,
    "end": 928.96,
    "duration": 28.88,
    "speechEnd": 928.48,
    "overlay": "ripples",
    "transition": "하드컷"
  },
  {
    "id": "S33",
    "index": 33,
    "type": "climax",
    "purpose": "물을 밀며 탈출한다",
    "start": 928.96,
    "end": 967.8,
    "duration": 38.84,
    "speechEnd": 967.8,
    "overlay": "photo",
    "transition": "하드컷"
  },
  {
    "id": "S34",
    "index": 34,
    "type": "reveal",
    "purpose": "등불이 마흔셋까지 켜진다",
    "start": 967.8,
    "end": 997.8,
    "duration": 30.0,
    "speechEnd": 997.5,
    "overlay": "lanterns",
    "transition": "슬로 페이드"
  },
  {
    "id": "S35",
    "index": 35,
    "type": "outro",
    "purpose": "쓴 적 없는 줄이 수첩에 추가돼 있다",
    "start": 997.8,
    "end": 1029.82,
    "duration": 32.02,
    "speechEnd": 1025.78,
    "overlay": "wetline",
    "transition": "암전"
  }
];
