import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const P=path.dirname(new URL(import.meta.url).pathname),id=path.basename(P);
const read=f=>JSON.parse(fs.readFileSync(path.join(P,f)));
const put=(f,v)=>fs.writeFileSync(path.join(P,f),JSON.stringify(v,null,2)+'\n');
const reports=['youtube-media-check','layout-main-check','motion-check','sync-check','publish-check','shorts-media-check','layout-shorts-check','shorts-originality-check','shorts-timeline-check','shorts-audio-review'];
for(const report of reports)if(read('05_review/'+report+'.json').status!=='pass')throw Error('Failed '+report);
const state=read('00_brief/production-state.json');
if(!state.shorts_script_approved)throw Error('Separate Short approval missing');
const metadata=read('06_delivery/delivery-metadata.json');
const digest=async f=>{const h=createHash('sha256');for await(const b of fs.createReadStream(path.join(P,f)))h.update(b);return h.digest('hex')};
if(await digest(`06_delivery/youtube/${id}-youtube.mp4`)!==metadata.master_sha256)throw Error('Completed main master changed');
const shortFile=`06_delivery/shorts/${id}-shorts.mp4`;
const shortFiles=[shortFile,'03_sync/shorts-captions.srt','03_sync/shorts-captions.vtt','07_publish/shorts/shorts-publish.html','07_publish/shorts/shorts-publish.md'];
for(const f of shortFiles)if(!fs.existsSync(path.join(P,f)))throw Error('Missing '+f);
for(const ext of ['srt','vtt'])fs.copyFileSync(path.join(P,`03_sync/shorts-captions.${ext}`),path.join(P,`06_delivery/shorts/shorts-captions.${ext}`));
const assets=read('04_composition/image-sources.json');
for(const a of assets){if(!path.isAbsolute(a.file))a.file=path.join(P,'04_composition',a.file);const h=createHash('sha256').update(fs.readFileSync(a.file)).digest('hex');if(h!==a.sha256||!a.render_approved)throw Error('Changed or unapproved '+a.id)}
put('04_composition/image-sources.json',assets);
const media=read('05_review/shorts-media-check.json');
const v=media.metadata.streams.find(s=>s.codec_type==='video');
Object.assign(metadata,{shorts_status:'verified',shorts_duration_seconds:Number(v.duration),shorts_width:v.width,shorts_height:v.height,shorts_fps:60,shorts_master_sha256:await digest(shortFile),shorts_visuals:6,shorts_voice_multiplier:1.07,shorts_caption_delivery:'burned_white_black_outline_and_external_srt_vtt',assets:[...new Set([...metadata.assets,...shortFiles])],project_complete:true,github_final_push:false,git_note:'Completion snapshot before authorized Git push; confirm remote branch separately.',subjective_listening_review:'Not claimed. Technical speech verification passed; playback available in helper.'});
put('06_delivery/delivery-metadata.json',metadata);
Object.assign(state,{status:'production_complete',shorts_status:'verified',shorts_script_approved:true,shorts_rendered:true,shorts_verified:true,publishing_package_finished:true,github_final_push:false,note:'Main and independently composed Short delivered. Main MP4 hash unchanged. Technical audio, image, timing, media and helper checks passed; human listening is not claimed. Git push follows this completion snapshot.'});
put('00_brief/production-state.json',state);
const checklist=path.join(P,'05_review/checklist.md');
let text=fs.readFileSync(checklist,'utf8');
text=text.replace('## 남은 승인 및 작업','## 독립 쇼츠 및 Git');
text=text.replace('- [ ] 독립 쇼츠 원고 별도 승인.','- [x] 독립 쇼츠 원고 별도 제작 승인.');
text=text.replace('- [ ] 승인 후 신규 세로 이미지 6장, 새 음성 및 1.07배 후처리, 1080x1920 60fps 쇼츠·자막·게시 패키지 검수.','- [x] 신규 세로 이미지 6장 두 차례 검수, 새 Bin 음성 및 1.07배 후처리, 26.6초 1080x1920 60fps 쇼츠·번인 자막·SRT/VTT·게시 패키지 검수. 음성은 기술 검사이며 사람의 청취를 주장하지 않음.');
text=text.replace('쇼츠와 전체 프로젝트 완료·Git 푸시는 아직 주장하지 않습니다.','본편과 독립 쇼츠 제작은 완료했습니다. 이 기록 저장 시점에는 Git 푸시 전이며 원격 확인은 별도로 진행합니다.');
fs.writeFileSync(checklist,text);
console.log('Main unchanged. Independent Short and publishing package verified; ready for scoped Git push.');
