import fs from 'node:fs';
import path from 'node:path';
const P=path.dirname(new URL(import.meta.url).pathname);
const read=n=>JSON.parse(fs.readFileSync(path.join(P,n)));
const put=(n,v)=>fs.writeFileSync(path.join(P,n),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const text=fs.readFileSync(path.join(P,'01_script/shorts-narration.txt'),'utf8');
if(/\d/.test(text))throw Error('Digits in approved narration');
put('01_script/shorts-tts-narration.txt',text);
const config=read('02_audio/elevenlabs-request.json');
config.script_source='../01_script/shorts-narration.txt';
config.tts_script_source='../01_script/shorts-tts-narration.txt';
config.target_audio='inbox/'+path.basename(P)+'-shorts.mp3';
delete config.bgm;
put('02_audio/elevenlabs-shorts-request.json',config);
const state=read('00_brief/production-state.json');
Object.assign(state,{shorts_script_approved:true,shorts_status:'producing',status:'shorts_production',note:'After the separately presented six-paragraph teaser, the user explicitly requested 쇼츠도 만들어줘. Proceed with this script, the approved project visual direction, Bin and cand-03. Long-form master remains unchanged.'});
put('00_brief/production-state.json',state);
fs.appendFileSync(path.join(P,'00_brief/approval-record.md'),'\n## 독립 쇼츠 제작 승인\n\n별도 제시한 여섯 문단 티저에 대해 사용자가 “쇼츠도 만들어줘”라고 제작을 요청했다. 해당 원고와 본 프로젝트의 승인된 화면 방향·Bin·cand-03로 독립 쇼츠를 제작한다. 본편 이미지/프레임/음성을 재사용하지 않는다.\n');
put('01_script/shorts-review.md','# 독립 쇼츠 원고 검수\n\n사용자 별도 제작 승인: “쇼츠도 만들어줘”. 앞서 제시한 여섯 문단 원고 그대로 사용한다.\n\n첫 문장에서 장화의 수면 이동을 제시한다. 사라진 장화 → 젖은 손바닥 흔적 → 고무 밑창 소리 → 다가오는 두 짝 → 난간에 올라온 한 짝으로 압축한다. 마지막 문장은 완결된다. 장화 안의 팔과 귀신의 정체, 구조 방법, 사진 결말은 공개하지 않는다. 숫자 없음, 설명형 메타 멘트 없음.\n\n신규 세로 이미지 여섯 장, 별도 Bin V3 음성, 피치 보존 1.07배, 120ms 시작 여백, 15~40초 최종 길이, 의미 단위 흰색/검정 테두리 자막. 본편은 변경하지 않는다.\n');
console.log('Approved independent Short sources prepared.');
